# Accuracy Testing

Evaluate accuracy of custom Tridiagonal Solver output against linalg.solve from file

In [ ]:
import numpy as np

def tridiagonal_to_matrix_system(a, b, c, d):
    n = len(b)
    A = np.zeros((n, n))
    np.fill_diagonal(A[1:], a)
    np.fill_diagonal(A, b)
    np.fill_diagonal(A[:, 1:], c)
    return A, d

# Example usage:
a = np.array([48, 29, 12, 8, 40, 61, 8, 6, 46 , 0])  # Lower diagonal
b = np.array([180, 222, 226, 106, 116, 180, 215, 177, 250, 119])  # Main diagonal
c = np.array([59, 51, 65, 24, 26, 25, 28, 95, 96, 0])  # Upper diagonal
d = np.array([94, 44, 41, 97, 89, 65, 7, 6, 53, 48])  # Right-hand side

A, rhs = tridiagonal_to_matrix_system(a, b, c, d)
print(A)
x = np.linalg.solve(A, rhs)

print("Solution using np.linalg.solve:", x)

x_pcr = np.array([0.487785, 0.105061, -0.053673, 0.770513, 0.665404, 0.217269, -0.028982, -0.000799, 0.067087, 0.377429])

# Compute accuracy (absolute error)
absolute_error = np.linalg.norm(x - x_pcr)
print(absolute_error)

[[180.  59.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 48. 222.  51.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  29. 226.  65.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  12. 106.  24.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   8. 116.  26.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  40. 180.  25.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  61. 215.  28.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   8. 177.  95.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   6. 250.  96.]
 [  0.   0.   0.   0.   0.   0.   0.   0.  46. 119.]]
Solution using np.linalg.solve: [ 0.48778544  0.10506138 -0.0536731   0.77051294  0.6654044   0.21726868
 -0.02898152 -0.00079869  0.06708653  0.37742873]
1.111652447640599e-06


In [ ]:
import numpy as np

def read_systems_from_file(file_path):
    with open(file_path, 'r') as file:
        num_systems = int(file.readline().strip())
        systems = []
        for _ in range(num_systems):
            a = np.array(list(map(float, file.readline().split())))
            b = np.array(list(map(float, file.readline().split())))
            c = np.array(list(map(float, file.readline().split())))
            d = np.array(list(map(float, file.readline().split())))
            result = np.array(list(map(float, file.readline().split())))
            systems.append((a, b, c, d, result))
    return systems

def tridiagonal_to_matrix_system(a, b, c, d):
    n = len(b)
    A = np.zeros((n, n))
    np.fill_diagonal(A[1:], a)
    np.fill_diagonal(A, b)
    np.fill_diagonal(A[:, 1:], c)
    return A, d

def evaluate_systems(systems):
    absolute_errors = []
    for a, b, c, d, result in systems:
        A, rhs = tridiagonal_to_matrix_system(a, b, c, d)
        x = np.linalg.solve(A, rhs)
        absolute_error = np.linalg.norm(x - result, ord=np.inf)  # Maximum absolute error
        absolute_errors.append(absolute_error)
    average_loss = np.mean(absolute_errors)
    return average_loss

file_path = 'results.txt'
systems = read_systems_from_file(file_path)
average_loss = evaluate_systems(systems)
print("Average loss:", average_loss)

Average loss: 4.959854797250557e-07
