# Accuracy Testing

Evaluate accuracy of custom Tridiagonal Solver output against linalg.solve from file

In [ ]:
# For Block

import numpy as np
BLOCK_SIZE = 2
n = 128

def tridiagonal_to_matrix_system(a, b, c, d):
    A = np.zeros((n*BLOCK_SIZE, n*BLOCK_SIZE))
    rows = n * BLOCK_SIZE
    last_ind = rows * rows
    # Fill in the main diagonal blocks
    index = 0
    for i in range(0, rows, BLOCK_SIZE):
        for j in range (0, BLOCK_SIZE):
            for k in range (0, BLOCK_SIZE):
                A[i+j][i+k] = b[index]
                index += 1
                # 0,0 0,1 1,0 1,1 // 2,2 2,3 3,2 3,3

    index = 0
    for i in range(0, rows - BLOCK_SIZE, BLOCK_SIZE):
        for j in range(0, BLOCK_SIZE):
            for k in range(BLOCK_SIZE, 2*BLOCK_SIZE):
                A[i+j][i+k] = c[index]
                index += 1
                # 0,2 0,3 1,2 1,3 2,4...

    index = 4
    for i in range(0, rows - BLOCK_SIZE, BLOCK_SIZE):
        for j in range(BLOCK_SIZE, 2*BLOCK_SIZE):
            for k in range(0, BLOCK_SIZE):
                A[i+j][i+k] = a[index]
                index += 1

    return A, d

np.set_printoptions(suppress=True)
# Example usage:
a = np.array([0.000000, 0.000000, 0.000000, 0.000000, 54.000000, 90.000000, 21.000000, 81.000000, 94.000000, 98.000000, 77.000000, 3.000000, 84.000000, 66.000000, 8.000000, 60.000000, 27.000000, 95.000000, 75.000000, 63.000000, 56.000000, 31.000000, 41.000000, 70.000000, 31.000000, 40.000000, 78.000000, 66.000000, 70.000000, 46.000000, 70.000000, 16.000000, 94.000000, 32.000000, 42.000000, 82.000000, 89.000000, 88.000000, 59.000000, 94.000000, 92.000000, 85.000000, 70.000000, 84.000000, 91.000000, 51.000000, 71.000000, 79.000000, 23.000000, 75.000000, 1.000000, 57.000000, 72.000000, 88.000000, 78.000000, 19.000000, 54.000000, 9.000000, 1.000000, 52.000000, 6.000000, 33.000000, 100.000000, 2.000000, 20.000000, 45.000000, 8.000000, 55.000000, 69.000000, 12.000000, 78.000000, 9.000000, 39.000000, 40.000000, 95.000000, 47.000000, 98.000000, 17.000000, 84.000000, 72.000000, 8.000000, 44.000000, 37.000000, 10.000000, 51.000000, 88.000000, 91.000000, 63.000000, 15.000000, 44.000000, 57.000000, 59.000000, 34.000000, 81.000000, 54.000000, 72.000000, 31.000000, 39.000000, 1.000000, 35.000000, 56.000000, 41.000000, 99.000000, 67.000000, 36.000000, 54.000000, 66.000000, 73.000000, 41.000000, 3.000000, 84.000000, 89.000000, 63.000000, 94.000000, 44.000000, 14.000000, 39.000000, 11.000000, 46.000000, 4.000000, 82.000000, 90.000000, 32.000000, 47.000000, 62.000000, 35.000000, 37.000000, 52.000000, 16.000000, 35.000000, 91.000000, 44.000000, 81.000000, 6.000000, 83.000000, 97.000000, 5.000000, 71.000000, 20.000000, 40.000000, 85.000000, 43.000000, 2.000000, 73.000000, 52.000000, 84.000000, 32.000000, 36.000000, 6.000000, 86.000000, 85.000000, 35.000000, 73.000000, 32.000000, 60.000000, 20.000000, 96.000000, 78.000000, 17.000000, 31.000000, 4.000000, 30.000000, 100.000000, 99.000000, 31.000000, 79.000000, 43.000000, 76.000000, 100.000000, 33.000000, 66.000000, 37.000000, 35.000000, 14.000000, 98.000000, 38.000000, 18.000000, 21.000000, 83.000000, 60.000000, 38.000000, 53.000000, 39.000000, 20.000000, 28.000000, 74.000000, 77.000000, 33.000000, 22.000000, 62.000000, 30.000000, 34.000000, 3.000000, 38.000000, 87.000000, 30.000000, 51.000000, 38.000000, 22.000000, 50.000000, 6.000000, 8.000000, 91.000000, 41.000000, 24.000000, 85.000000, 16.000000, 32.000000, 57.000000, 25.000000, 95.000000, 4.000000, 56.000000, 41.000000, 79.000000, 100.000000, 75.000000, 36.000000, 63.000000, 82.000000, 49.000000, 49.000000, 12.000000, 44.000000, 30.000000, 9.000000, 61.000000, 37.000000, 74.000000, 47.000000, 4.000000, 51.000000, 95.000000, 82.000000, 48.000000, 74.000000, 90.000000, 17.000000, 34.000000, 50.000000, 92.000000, 56.000000, 45.000000, 19.000000, 69.000000, 75.000000, 35.000000, 76.000000, 37.000000, 30.000000, 86.000000, 7.000000, 40.000000, 49.000000, 77.000000, 55.000000, 41.000000, 1.000000, 69.000000, 72.000000, 8.000000, 27.000000, 83.000000, 71.000000, 20.000000, 32.000000, 82.000000, 58.000000, 29.000000, 80.000000, 9.000000, 11.000000, 42.000000, 45.000000, 96.000000, 58.000000, 57.000000, 80.000000, 2.000000, 62.000000, 35.000000, 13.000000, 98.000000, 34.000000, 69.000000, 30.000000, 21.000000, 85.000000, 70.000000, 50.000000, 95.000000, 64.000000, 36.000000, 89.000000, 50.000000, 33.000000, 26.000000, 10.000000, 94.000000, 58.000000, 81.000000, 73.000000, 95.000000, 88.000000, 50.000000, 74.000000, 71.000000, 96.000000, 81.000000, 27.000000, 47.000000, 76.000000, 78.000000, 49.000000, 76.000000, 79.000000, 86.000000, 71.000000, 68.000000, 48.000000, 60.000000, 97.000000, 27.000000, 85.000000, 61.000000, 54.000000, 98.000000, 20.000000, 31.000000, 74.000000, 8.000000, 16.000000, 18.000000, 9.000000, 76.000000, 68.000000, 63.000000, 82.000000, 20.000000, 58.000000, 78.000000, 69.000000, 64.000000, 88.000000, 88.000000, 45.000000, 33.000000, 88.000000, 86.000000, 93.000000, 9.000000, 41.000000, 89.000000, 27.000000, 91.000000, 94.000000, 37.000000, 69.000000, 10.000000, 89.000000, 80.000000, 94.000000, 94.000000, 49.000000, 21.000000, 80.000000, 98.000000, 37.000000, 30.000000, 44.000000, 90.000000, 95.000000, 29.000000, 7.000000, 68.000000, 48.000000, 94.000000, 88.000000, 20.000000, 75.000000, 46.000000, 93.000000, 55.000000, 72.000000, 19.000000, 90.000000, 27.000000, 65.000000, 78.000000, 71.000000, 35.000000, 49.000000, 7.000000, 6.000000, 45.000000, 94.000000, 82.000000, 60.000000, 62.000000, 23.000000, 29.000000, 77.000000, 59.000000, 6.000000, 25.000000, 35.000000, 84.000000, 65.000000, 69.000000, 11.000000, 70.000000, 90.000000, 65.000000, 47.000000, 61.000000, 77.000000, 33.000000, 6.000000, 61.000000, 79.000000, 79.000000, 95.000000, 78.000000, 84.000000, 70.000000, 31.000000, 10.000000, 87.000000, 25.000000, 35.000000, 41.000000, 73.000000, 6.000000, 98.000000, 59.000000, 61.000000, 93.000000, 88.000000, 14.000000, 88.000000, 23.000000, 90.000000, 29.000000, 4.000000, 15.000000, 73.000000, 55.000000, 93.000000, 96.000000, 76.000000, 7.000000, 73.000000, 18.000000, 69.000000, 61.000000, 67.000000, 66.000000, 18.000000, 57.000000, 65.000000, 22.000000, 70.000000, 85.000000, 71.000000, 26.000000, 8.000000, 30.000000, 84.000000, 62.000000, 24.000000, 59.000000, 92.000000, 12.000000, 48.000000, 7.000000, 3.000000, 8.000000, 28.000000, 7.000000, 40.000000, 54.000000, 8.000000, 73.000000, 67.000000, 62.000000, 16.000000, 2.000000, 29.000000, 19.000000, 80.000000, 76.000000, 29.000000, 7.000000, 52.000000, 80.000000, 18.000000, 76.000000, 32.000000, 21.000000, 57.000000, 15.000000, 53.000000, 14.000000, 10.000000, 91.000000, 65.000000, 34.000000, 10.000000, 67.000000, 58.000000, 44.000000, 95.000000])  # Lower diagonal
b = np.array([29.000000, 67.000000, 14.000000, 43.000000, 53.000000, 16.000000, 68.000000, 29.000000, 89.000000, 42.000000, 24.000000, 11.000000, 77.000000, 62.000000, 58.000000, 39.000000, 89.000000, 53.000000, 24.000000, 25.000000, 47.000000, 27.000000, 86.000000, 11.000000, 89.000000, 8.000000, 48.000000, 19.000000, 84.000000, 99.000000, 41.000000, 86.000000, 14.000000, 8.000000, 9.000000, 69.000000, 8.000000, 93.000000, 53.000000, 75.000000, 4.000000, 64.000000, 17.000000, 38.000000, 42.000000, 84.000000, 4.000000, 93.000000, 51.000000, 3.000000, 28.000000, 16.000000, 50.000000, 67.000000, 25.000000, 64.000000, 96.000000, 15.000000, 44.000000, 14.000000, 80.000000, 30.000000, 50.000000, 56.000000, 53.000000, 99.000000, 68.000000, 15.000000, 89.000000, 37.000000, 85.000000, 94.000000, 22.000000, 41.000000, 86.000000, 52.000000, 72.000000, 1.000000, 30.000000, 14.000000, 51.000000, 24.000000, 96.000000, 74.000000, 19.000000, 8.000000, 8.000000, 11.000000, 35.000000, 70.000000, 34.000000, 6.000000, 69.000000, 70.000000, 66.000000, 13.000000, 56.000000, 68.000000, 63.000000, 29.000000, 54.000000, 75.000000, 32.000000, 50.000000, 19.000000, 26.000000, 72.000000, 84.000000, 58.000000, 79.000000, 56.000000, 43.000000, 63.000000, 16.000000, 22.000000, 51.000000, 63.000000, 65.000000, 68.000000, 57.000000, 1.000000, 38.000000, 73.000000, 26.000000, 15.000000, 8.000000, 67.000000, 98.000000, 21.000000, 46.000000, 7.000000, 8.000000, 71.000000, 28.000000, 32.000000, 97.000000, 53.000000, 70.000000, 81.000000, 99.000000, 99.000000, 87.000000, 59.000000, 77.000000, 60.000000, 77.000000, 31.000000, 39.000000, 63.000000, 74.000000, 75.000000, 71.000000, 47.000000, 33.000000, 49.000000, 13.000000, 82.000000, 24.000000, 34.000000, 82.000000, 19.000000, 99.000000, 80.000000, 33.000000, 89.000000, 81.000000, 4.000000, 62.000000, 26.000000, 27.000000, 16.000000, 87.000000, 30.000000, 9.000000, 95.000000, 52.000000, 56.000000, 38.000000, 88.000000, 69.000000, 53.000000, 18.000000, 35.000000, 98.000000, 43.000000, 70.000000, 88.000000, 33.000000, 77.000000, 57.000000, 2.000000, 84.000000, 99.000000, 32.000000, 61.000000, 80.000000, 17.000000, 26.000000, 17.000000, 19.000000, 10.000000, 53.000000, 34.000000, 38.000000, 70.000000, 76.000000, 10.000000, 28.000000, 67.000000, 68.000000, 49.000000, 64.000000, 81.000000, 87.000000, 79.000000, 1.000000, 25.000000, 38.000000, 21.000000, 6.000000, 96.000000, 45.000000, 36.000000, 67.000000, 74.000000, 17.000000, 76.000000, 66.000000, 16.000000, 91.000000, 13.000000, 90.000000, 74.000000, 99.000000, 54.000000, 61.000000, 42.000000, 10.000000, 93.000000, 57.000000, 21.000000, 34.000000, 58.000000, 77.000000, 78.000000, 87.000000, 60.000000, 69.000000, 52.000000, 84.000000, 20.000000, 5.000000, 37.000000, 49.000000, 13.000000, 98.000000, 77.000000, 72.000000, 100.000000, 30.000000, 51.000000, 79.000000, 4.000000, 99.000000, 63.000000, 100.000000, 72.000000, 22.000000, 9.000000, 73.000000, 27.000000, 86.000000, 37.000000, 35.000000, 10.000000, 91.000000, 13.000000, 86.000000, 28.000000, 46.000000, 70.000000, 21.000000, 54.000000, 9.000000, 84.000000, 94.000000, 85.000000, 33.000000, 13.000000, 72.000000, 92.000000, 71.000000, 94.000000, 62.000000, 25.000000, 45.000000, 74.000000, 34.000000, 47.000000, 69.000000, 30.000000, 50.000000, 72.000000, 76.000000, 51.000000, 8.000000, 85.000000, 46.000000, 29.000000, 60.000000, 38.000000, 79.000000, 7.000000, 76.000000, 42.000000, 44.000000, 71.000000, 59.000000, 44.000000, 34.000000, 57.000000, 51.000000, 40.000000, 16.000000, 93.000000, 95.000000, 68.000000, 87.000000, 39.000000, 68.000000, 92.000000, 44.000000, 72.000000, 1.000000, 6.000000, 88.000000, 56.000000, 46.000000, 56.000000, 65.000000, 33.000000, 97.000000, 39.000000, 65.000000, 52.000000, 92.000000, 81.000000, 41.000000, 80.000000, 92.000000, 63.000000, 1.000000, 56.000000, 20.000000, 60.000000, 67.000000, 40.000000, 42.000000, 15.000000, 46.000000, 54.000000, 35.000000, 79.000000, 10.000000, 80.000000, 95.000000, 94.000000, 81.000000, 4.000000, 72.000000, 47.000000, 63.000000, 66.000000, 48.000000, 20.000000, 37.000000, 39.000000, 62.000000, 93.000000, 13.000000, 63.000000, 59.000000, 47.000000, 88.000000, 49.000000, 89.000000, 78.000000, 3.000000, 9.000000, 7.000000, 97.000000, 82.000000, 48.000000, 20.000000, 59.000000, 98.000000, 82.000000, 53.000000, 43.000000, 59.000000, 69.000000, 23.000000, 83.000000, 15.000000, 65.000000, 56.000000, 22.000000, 56.000000, 67.000000, 49.000000, 16.000000, 32.000000, 7.000000, 86.000000, 10.000000, 27.000000, 78.000000, 87.000000, 10.000000, 55.000000, 80.000000, 82.000000, 93.000000, 10.000000, 2.000000, 81.000000, 96.000000, 75.000000, 74.000000, 84.000000, 67.000000, 40.000000, 76.000000, 59.000000, 7.000000, 31.000000, 39.000000, 4.000000, 29.000000, 32.000000, 66.000000, 94.000000, 52.000000, 93.000000, 55.000000, 99.000000, 1.000000, 40.000000, 56.000000, 6.000000, 49.000000, 15.000000, 35.000000, 4.000000, 31.000000, 23.000000, 55.000000, 26.000000, 11.000000, 35.000000, 82.000000, 69.000000, 37.000000, 8.000000, 45.000000, 6.000000, 21.000000, 28.000000, 34.000000, 15.000000, 2.000000, 14.000000, 95.000000, 44.000000, 54.000000, 35.000000, 28.000000, 91.000000, 10.000000, 45.000000, 1.000000, 79.000000, 93.000000, 77.000000, 38.000000, 7.000000, 5.000000, 90.000000, 37.000000, 7.000000, 87.000000, 10.000000, 96.000000, 30.000000, 23.000000, 70.000000, 24.000000, 58.000000, 99.000000, 31.000000, 68.000000, 13.000000, 33.000000, 68.000000, 16.000000, 31.000000, 47.000000, 43.000000, 87.000000, 65.000000, 5.000000, 10.000000])  # Main diagonal
c = np.array([36.000000, 28.000000, 83.000000, 33.000000, 97.000000, 82.000000, 99.000000, 64.000000, 72.000000, 50.000000, 70.000000, 81.000000, 60.000000, 73.000000, 79.000000, 68.000000, 40.000000, 20.000000, 66.000000, 63.000000, 91.000000, 94.000000, 77.000000, 42.000000, 2.000000, 61.000000, 88.000000, 34.000000, 8.000000, 23.000000, 78.000000, 61.000000, 1.000000, 22.000000, 52.000000, 91.000000, 20.000000, 38.000000, 7.000000, 52.000000, 74.000000, 89.000000, 35.000000, 66.000000, 7.000000, 40.000000, 80.000000, 20.000000, 78.000000, 71.000000, 15.000000, 99.000000, 20.000000, 55.000000, 97.000000, 47.000000, 18.000000, 48.000000, 22.000000, 49.000000, 49.000000, 57.000000, 29.000000, 68.000000, 45.000000, 15.000000, 69.000000, 77.000000, 30.000000, 33.000000, 38.000000, 22.000000, 73.000000, 26.000000, 46.000000, 90.000000, 49.000000, 4.000000, 72.000000, 36.000000, 13.000000, 21.000000, 11.000000, 50.000000, 97.000000, 95.000000, 44.000000, 61.000000, 96.000000, 67.000000, 74.000000, 69.000000, 58.000000, 67.000000, 69.000000, 56.000000, 47.000000, 61.000000, 75.000000, 70.000000, 78.000000, 88.000000, 21.000000, 1.000000, 7.000000, 30.000000, 61.000000, 51.000000, 51.000000, 38.000000, 45.000000, 86.000000, 36.000000, 2.000000, 89.000000, 42.000000, 59.000000, 32.000000, 72.000000, 26.000000, 61.000000, 50.000000, 12.000000, 58.000000, 53.000000, 66.000000, 4.000000, 66.000000, 12.000000, 67.000000, 100.000000, 89.000000, 21.000000, 19.000000, 32.000000, 66.000000, 54.000000, 57.000000, 25.000000, 59.000000, 2.000000, 45.000000, 77.000000, 34.000000, 17.000000, 13.000000, 69.000000, 91.000000, 10.000000, 49.000000, 86.000000, 80.000000, 82.000000, 54.000000, 5.000000, 40.000000, 24.000000, 59.000000, 64.000000, 2.000000, 38.000000, 72.000000, 44.000000, 27.000000, 87.000000, 58.000000, 53.000000, 83.000000, 99.000000, 29.000000, 85.000000, 14.000000, 66.000000, 64.000000, 46.000000, 76.000000, 18.000000, 94.000000, 45.000000, 29.000000, 46.000000, 82.000000, 16.000000, 81.000000, 30.000000, 68.000000, 37.000000, 58.000000, 92.000000, 3.000000, 40.000000, 92.000000, 82.000000, 53.000000, 33.000000, 6.000000, 83.000000, 67.000000, 40.000000, 1.000000, 30.000000, 15.000000, 18.000000, 55.000000, 41.000000, 22.000000, 73.000000, 62.000000, 84.000000, 33.000000, 91.000000, 98.000000, 40.000000, 32.000000, 56.000000, 92.000000, 7.000000, 91.000000, 99.000000, 76.000000, 70.000000, 26.000000, 33.000000, 26.000000, 56.000000, 55.000000, 82.000000, 17.000000, 32.000000, 65.000000, 13.000000, 13.000000, 25.000000, 68.000000, 50.000000, 10.000000, 22.000000, 10.000000, 83.000000, 81.000000, 84.000000, 86.000000, 32.000000, 13.000000, 13.000000, 86.000000, 27.000000, 44.000000, 29.000000, 30.000000, 22.000000, 77.000000, 74.000000, 44.000000, 12.000000, 38.000000, 72.000000, 99.000000, 36.000000, 65.000000, 2.000000, 8.000000, 99.000000, 99.000000, 76.000000, 30.000000, 22.000000, 22.000000, 43.000000, 66.000000, 73.000000, 51.000000, 34.000000, 4.000000, 75.000000, 59.000000, 92.000000, 49.000000, 29.000000, 8.000000, 69.000000, 79.000000, 72.000000, 69.000000, 64.000000, 21.000000, 29.000000, 9.000000, 62.000000, 23.000000, 9.000000, 21.000000, 71.000000, 4.000000, 24.000000, 6.000000, 78.000000, 62.000000, 31.000000, 32.000000, 26.000000, 42.000000, 77.000000, 18.000000, 67.000000, 51.000000, 28.000000, 89.000000, 34.000000, 91.000000, 71.000000, 95.000000, 89.000000, 77.000000, 26.000000, 51.000000, 73.000000, 20.000000, 100.000000, 78.000000, 25.000000, 100.000000, 29.000000, 78.000000, 53.000000, 31.000000, 69.000000, 91.000000, 10.000000, 58.000000, 17.000000, 65.000000, 91.000000, 75.000000, 87.000000, 41.000000, 38.000000, 9.000000, 39.000000, 13.000000, 72.000000, 87.000000, 4.000000, 65.000000, 40.000000, 8.000000, 22.000000, 3.000000, 22.000000, 32.000000, 9.000000, 29.000000, 93.000000, 32.000000, 71.000000, 16.000000, 48.000000, 87.000000, 72.000000, 16.000000, 24.000000, 16.000000, 4.000000, 30.000000, 73.000000, 66.000000, 3.000000, 71.000000, 80.000000, 20.000000, 51.000000, 44.000000, 89.000000, 90.000000, 10.000000, 41.000000, 38.000000, 26.000000, 55.000000, 98.000000, 39.000000, 34.000000, 14.000000, 73.000000, 40.000000, 39.000000, 33.000000, 72.000000, 91.000000, 65.000000, 11.000000, 55.000000, 9.000000, 80.000000, 51.000000, 40.000000, 66.000000, 83.000000, 60.000000, 82.000000, 16.000000, 65.000000, 23.000000, 80.000000, 25.000000, 18.000000, 99.000000, 10.000000, 24.000000, 46.000000, 74.000000, 2.000000, 60.000000, 17.000000, 93.000000, 28.000000, 63.000000, 80.000000, 48.000000, 11.000000, 32.000000, 21.000000, 37.000000, 84.000000, 96.000000, 25.000000, 57.000000, 14.000000, 26.000000, 4.000000, 83.000000, 29.000000, 6.000000, 42.000000, 63.000000, 93.000000, 2.000000, 40.000000, 65.000000, 51.000000, 43.000000, 15.000000, 20.000000, 70.000000, 28.000000, 40.000000, 33.000000, 72.000000, 86.000000, 73.000000, 47.000000, 36.000000, 16.000000, 72.000000, 38.000000, 10.000000, 64.000000, 8.000000, 55.000000, 30.000000, 88.000000, 12.000000, 30.000000, 98.000000, 11.000000, 29.000000, 94.000000, 11.000000, 20.000000, 84.000000, 57.000000, 27.000000, 63.000000, 85.000000, 10.000000, 17.000000, 99.000000, 34.000000, 95.000000, 71.000000, 81.000000, 24.000000, 35.000000, 35.000000, 41.000000, 96.000000, 55.000000, 83.000000, 41.000000, 33.000000, 38.000000, 45.000000, 69.000000, 35.000000, 97.000000, 64.000000, 65.000000, 45.000000, 16.000000, 95.000000, 23.000000, 51.000000, 57.000000, 8.000000, 40.000000, 57.000000, 84.000000, 15.000000, 0.000000, 0.000000, 0.000000, 0.00000])  # Upper diagonal
d = np.array([27.000000, 15.000000, 63.000000, 29.000000, 79.000000, 76.000000, 85.000000, 11.000000, 37.000000, 45.000000, 30.000000, 28.000000, 84.000000, 97.000000, 92.000000, 92.000000, 27.000000, 78.000000, 75.000000, 25.000000, 87.000000, 41.000000, 68.000000, 53.000000, 27.000000, 77.000000, 70.000000, 22.000000, 81.000000, 16.000000, 32.000000, 59.000000, 30.000000, 46.000000, 87.000000, 8.000000, 21.000000, 24.000000, 19.000000, 58.000000, 20.000000, 100.000000, 37.000000, 55.000000, 97.000000, 80.000000, 98.000000, 23.000000, 57.000000, 72.000000, 100.000000, 95.000000, 64.000000, 67.000000, 100.000000, 90.000000, 95.000000, 69.000000, 12.000000, 76.000000, 84.000000, 95.000000, 86.000000, 66.000000, 40.000000, 73.000000, 73.000000, 60.000000, 48.000000, 43.000000, 69.000000, 67.000000, 43.000000, 5.000000, 73.000000, 91.000000, 85.000000, 70.000000, 13.000000, 93.000000, 93.000000, 64.000000, 40.000000, 56.000000, 82.000000, 39.000000, 45.000000, 77.000000, 59.000000, 56.000000, 52.000000, 94.000000, 2.000000, 37.000000, 59.000000, 41.000000, 61.000000, 84.000000, 1.000000, 8.000000, 78.000000, 21.000000, 26.000000, 72.000000, 78.000000, 98.000000, 62.000000, 14.000000, 19.000000, 27.000000, 6.000000, 11.000000, 90.000000, 97.000000, 66.000000, 72.000000, 87.000000, 11.000000, 48.000000, 45.000000, 18.000000, 51.000000, 91.000000, 20.000000, 39.000000, 1.000000, 12.000000, 100.000000, 84.000000, 64.000000, 59.000000, 62.000000, 85.000000, 37.000000, 85.000000, 62.000000, 86.000000, 47.000000, 75.000000, 5.000000, 73.000000, 32.000000, 15.000000, 62.000000, 81.000000, 33.000000, 85.000000, 67.000000, 95.000000, 32.000000, 64.000000, 64.000000, 82.000000, 54.000000, 35.000000, 21.000000, 54.000000, 47.000000, 72.000000, 90.000000, 10.000000, 82.000000, 3.000000, 46.000000, 18.000000, 87.000000, 59.000000, 4.000000, 33.000000, 33.000000, 60.000000, 57.000000, 17.000000, 26.000000, 71.000000, 97.000000, 10.000000, 55.000000, 15.000000, 4.000000, 87.000000, 78.000000, 68.000000, 20.000000, 83.000000, 54.000000, 92.000000, 89.000000, 100.000000, 63.000000, 78.000000, 62.000000, 97.000000, 32.000000, 59.000000, 14.000000, 18.000000, 18.000000, 69.000000, 3.000000, 50.000000, 80.000000, 11.000000, 18.000000, 6.000000, 81.000000, 66.000000, 15.000000, 36.000000, 81.000000, 71.000000, 74.000000, 10.000000, 90.000000, 93.000000, 45.000000, 43.000000, 37.000000, 33.000000, 95.000000, 51.000000, 62.000000, 8.000000, 47.000000, 45.000000, 66.000000, 61.000000, 14.000000, 83.000000, 81.000000, 16.000000, 85.000000, 61.000000, 27.000000, 2.000000, 18.000000, 59.000000, 20.000000, 84.000000, 94.000000, 52.000000, 54.000000, 67.000000, 13.000000, 43.000000, 12.000000, 57.000000, 38.000000, 48.000000, 41.000000, 84.000000, 98.000000, 54.000000, 91.000000, 97.000000, 98.000000])  # Right-hand side

A, rhs = tridiagonal_to_matrix_system(a, b, c, d)
print(A)
x = np.linalg.solve(A, rhs)

print("Solution using np.linalg.solve:", x)

#_pcr = np.array([0.487785, 0.105061, -0.053673, 0.770513, 0.665404, 0.217269, -0.028982, -0.000799, 0.067087, 0.377429])

x_pcr = np.array([0.829741, -0.248835, -0.222413, 0.986215, -0.442614, 0.969913, -1.866309, 2.725541, -3.130275, 3.023340, -3.005019, 3.351491, 2.580375, -0.771147, 1.168675, -2.995503, -4.433959, 7.856696, -5.812431, 0.819768, -6.815887, -3.031258, -1.840807, 10.219896, -2.582035, 1.993845, -3.556788, -4.140515, 1.021742, 9.369178, -3.989847, 2.990425, -1.165937, 0.057764, 1.042217, -1.039628, 1.810002, 1.762679, -0.186739, -2.943040, -3.722106, 2.606844, 18.129110, 2.025624, -16.156174, 12.672466, -0.140209, -8.541337, -4.268719, 7.104430, 12.406666, -7.093748, 0.015151, -1.038122, -3.951661, 1.826154, 1.424008, 3.020985, 1.030451, -1.423810, 2.053955, -5.322500, 4.474388, 1.098222, 4.279188, -2.390262, -3.889810, -0.048629, -0.058647, 1.026635, -0.765019, 0.762499, -0.676210, 0.902079, -1.176141, 0.757909, 1.761966, -0.002439, 0.147067, 0.960584, -0.224220, -3.147283, -2.227537, 6.443289, 0.636704, -1.441567, 0.202360, 3.256953, 3.957551, -3.963816, -5.198099, 0.101363, 6.445188, 1.084046, 1.105788, -3.619917, -0.358213, 1.380187, -0.560221, 4.386325, -3.222030, 1.936263, -0.180350, -1.248030, 0.750177, 0.702853, 0.159292, 0.243761, 0.083538, -1.446242, -0.416695, 0.594098, 1.005751, 0.601524, -0.302412, 0.535257, 1.389641, -1.923617, 0.102733, 2.306958, -5.609888, 5.166651, -2.224085, 0.096847, -8.862534, 4.312235, 3.999541, 3.367516, -5.769863, 6.117693, 0.776432, -1.368148, 1.805871, 0.607137, 1.357615, -5.480388, 4.685323, 2.582558, 0.521453, -1.465405, -4.726634, 3.170937, -3.225817, 7.097065, -2.501046, 0.472939, -2.668350, 5.036924, 1.102465, -1.653678, -0.761901, 2.389844, -0.326198, 0.172508, 0.327036, -1.243441, -0.513016, 1.531319, -2.732688, 2.854970, 0.292751, 0.580538, 0.898566, -1.717153, 0.045375, 0.998366, 1.016812, 0.644586, -3.132294, 3.471747, -1.481732, -1.321789, 1.708153, 1.366783, -0.040825, -0.756254, -13.429972, 5.164989, 10.127622, -8.095366, -1.860658, 2.065987, 11.575823, -13.243728, 2.437802, 1.453494, 3.077066, -2.107933, 2.905281, -3.881659, 5.961021, -3.958459, 1.445699, 3.145338, -0.637844, 0.377668, -1.091379, -2.688931, 5.931078, 0.911814, -6.914627, 2.908634, -4.059310, 4.352928, 2.333467, 2.437386, -1.922296, 0.189621, -5.759879, 8.390936, -4.970719, 1.633916, -3.235031, 4.574365, -1.043027, 1.746248, -2.346784, 1.332689, 0.325206, -0.573743, -2.211837, 3.201102, -0.835865, -1.586764, 4.817019, -3.106612, 0.185533, -0.290854, -2.690583, 3.144400, 2.833737, -4.899082, -0.501080, 0.405763, 3.729174, 0.193379, 0.677179, -1.427298, -2.313375, 1.754934, -0.368565, 1.768102, 0.372284, -0.274322, -2.933883, 1.766935, -1.070058, 5.997921, -0.448439, -1.731800, 2.333943, -2.291295, 3.595572, -0.570727, -1.319127, 0.060945])

# Compute accuracy (absolute error)
for i in range(0, len(x_pcr)):
    #print(i)
    percentage = (abs(x_pcr[i] - x[i]) / x[i])*100
    #print(percentage)
    if percentage > 2 or percentage < -2:

        print("index: " + str(i) + ", my answer: " + str(x_pcr[i]) + ", correct answer: " + str(x[i]))
absolute_error = np.linalg.norm(x - x_pcr)
print(absolute_error)
print(len(x_pcr))


[[180.  59.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 48. 222.  51.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  29. 226.  65.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  12. 106.  24.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   8. 116.  26.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  40. 180.  25.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  61. 215.  28.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   8. 177.  95.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   6. 250.  96.]
 [  0.   0.   0.   0.   0.   0.   0.   0.  46. 119.]]
Solution using np.linalg.solve: [ 0.48778544  0.10506138 -0.0536731   0.77051294  0.6654044   0.21726868
 -0.02898152 -0.00079869  0.06708653  0.37742873]
1.111652447640599e-06


In [ ]:
import numpy as np

def read_systems_from_file(file_path):
    with open(file_path, 'r') as file:
        num_systems = int(file.readline().strip())
        systems = []
        for _ in range(num_systems):
            a = np.array(list(map(float, file.readline().split())))
            b = np.array(list(map(float, file.readline().split())))
            c = np.array(list(map(float, file.readline().split())))
            d = np.array(list(map(float, file.readline().split())))
            result = np.array(list(map(float, file.readline().split())))
            systems.append((a, b, c, d, result))
    return systems

def tridiagonal_to_matrix_system(a, b, c, d):
    n = len(b)
    A = np.zeros((n, n))
    np.fill_diagonal(A[1:], a)
    np.fill_diagonal(A, b)
    np.fill_diagonal(A[:, 1:], c)
    return A, d

def evaluate_systems(systems):
    absolute_errors = []
    for a, b, c, d, result in systems:
        A, rhs = tridiagonal_to_matrix_system(a, b, c, d)
        x = np.linalg.solve(A, rhs)
        absolute_error = np.linalg.norm(x - result, ord=np.inf)  # Maximum absolute error
        absolute_errors.append(absolute_error)
    average_loss = np.mean(absolute_errors)
    return average_loss

file_path = 'results.txt'
systems = read_systems_from_file(file_path)
average_loss = evaluate_systems(systems)
print("Average loss:", average_loss)

Average loss: 4.959854797250557e-07
